Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "Server"

  config.vm.network "public_network",
    ip: "10.42.0.173",
    bridge: "wlp11s0"

  config.vm.network "forwarded_port",
    guest: 80,
    host: 8080
    
  config.vm.network "forwarded_port",
    guest: 5601,
    host: 8081

  config.vm.provider "virtualbox" do |my_vm|
    my_vm.name = "Server"
    my_vm.memory = 4096
    my_vm.cpus = 2
  end

  #config.vm.provider "virtualbox" do |vb|
  #  vb.gui = true
  #end

  config.vm.provision "shell", path: "bootstrap.sh"
end