Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "Server"


  config.vm.network "forwarded_port",
    guest: 80,
    host: 8080
    
  config.vm.network "forwarded_port",
    guest: 5601,
    host: 8081

  config.vm.provider "libvirt" do |my_vm|
    my_vm.memory = 4096
    my_vm.cpus = 2
  end

  #config.vm.provider "virtualbox" do |vb|
  #  vb.gui = true
  #end

  config.vm.provision "shell", path: "bootstrap.sh"
end