- name: Provision System and Install Docker
  hosts: servers
  become: true
  roles:
    - role: preparing_server
      tags: setup_docker

- name: Configure Docker Daemon Proxy Settings
  hosts: servers
  become: true
  roles:
    - role: docker_proxy
      tags: preparing_proxy