events { 
    worker_connections 1024; 
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # CRITICAL: This line automatically loads any .conf file inside that folder
    include /etc/nginx/conf.d/*.conf;
}
